name: networker_ble
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  networker:
    path: ../networker
  quick_blue: ^0.5.0-dev.2
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
